apiVersion: apps/v1
kind: Deployment
metadata:
  name: tserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tserver
  template:
    metadata:
      labels:
        app: tserver
    spec:
      containers:
      - name: tserver
        image: docker.io/uablrek/tserver:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: SERVERS
          value: "All"
        ports:
        - name: mconnect
          containerPort: 5001
        - name: ctraffic
          containerPort: 5003
        - name: mconnect-udp
          protocol: UDP
          containerPort: 5001
        - name: ctraffic-udp
          protocol: UDP
          containerPort: 5003
        - name: "http"
          containerPort: 80
        - name: "kahttp"
          containerPort: 8080
        - name: "kahttps"
          containerPort: 8443
        - name: "sctpt"
          protocol: SCTP
          containerPort: 6000
        - name: "telnet"
          containerPort: 23
